[project]
name = "agh-space"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bitstruct>=8.21.0",
    "crccheck>=1.3.1",
    "nicegui>=3.1.0",
    "pyyaml>=6.0.3",
    "rich>=14.2.0",
]
